// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using bow.Infrastructure.Persistence;

#nullable disable

namespace bow.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260724182505_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("bow.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("LearningLanguage")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("learning_language");

                    b.Property<string>("LearningLevel")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("learning_level");

                    b.Property<string>("NativeLanguage")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("native_language");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at");

                    b.Property<long>("TelegramId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_id");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("TelegramId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_telegram_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("bow.Domain.Entities.UserVocabularyProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("LastReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_reviewed_at");

                    b.Property<DateTime>("NextReviewAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_review_at");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("stage");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("VocabularyItemId")
                        .HasColumnType("integer")
                        .HasColumnName("vocabulary_item_id");

                    b.HasKey("Id")
                        .HasName("pk_user_vocabulary_progresses");

                    b.HasIndex("VocabularyItemId")
                        .HasDatabaseName("ix_user_vocabulary_progresses_vocabulary_item_id");

                    b.HasIndex("UserId", "NextReviewAt")
                        .HasDatabaseName("ix_user_vocabulary_progresses_user_id_next_review_at");

                    b.HasIndex("UserId", "VocabularyItemId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_vocabulary_progresses_user_id_vocabulary_item_id");

                    b.ToTable("user_vocabulary_progresses", (string)null);
                });

            modelBuilder.Entity("bow.Domain.Entities.VocabularyItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("language");

                    b.Property<string>("NormalizedText")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("normalized_text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_vocabulary_items");

                    b.HasIndex("Language", "NormalizedText")
                        .IsUnique()
                        .HasDatabaseName("ix_vocabulary_items_language_normalized_text");

                    b.ToTable("vocabulary_items", (string)null);
                });

            modelBuilder.Entity("bow.Domain.Entities.VocabularyTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("level");

                    b.Property<int>("TranslationFromId")
                        .HasColumnType("integer")
                        .HasColumnName("translation_from_id");

                    b.Property<int>("TranslationToId")
                        .HasColumnType("integer")
                        .HasColumnName("translation_to_id");

                    b.HasKey("Id")
                        .HasName("pk_vocabulary_translations");

                    b.HasIndex("TranslationToId")
                        .HasDatabaseName("ix_vocabulary_translations_translation_to_id");

                    b.HasIndex("TranslationFromId", "TranslationToId")
                        .IsUnique()
                        .HasDatabaseName("ix_vocabulary_translations_translation_from_id_translation_to_");

                    b.ToTable("vocabulary_translations", (string)null);
                });

            modelBuilder.Entity("bow.Domain.Entities.UserVocabularyProgress", b =>
                {
                    b.HasOne("bow.Domain.Entities.User", "User")
                        .WithMany("UserVocabularyItemProgresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_vocabulary_progresses_users_user_id");

                    b.HasOne("bow.Domain.Entities.VocabularyItem", "VocabularyItem")
                        .WithMany("UserVocabularyItemProgresses")
                        .HasForeignKey("VocabularyItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_vocabulary_progresses_vocabulary_items_vocabulary_item");

                    b.Navigation("User");

                    b.Navigation("VocabularyItem");
                });

            modelBuilder.Entity("bow.Domain.Entities.VocabularyTranslation", b =>
                {
                    b.HasOne("bow.Domain.Entities.VocabularyItem", "TranslationFrom")
                        .WithMany("SourceTranslations")
                        .HasForeignKey("TranslationFromId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vocabulary_translations_vocabulary_items_translation_from_id");

                    b.HasOne("bow.Domain.Entities.VocabularyItem", "TranslationTo")
                        .WithMany("TargetTranslations")
                        .HasForeignKey("TranslationToId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vocabulary_translations_vocabulary_items_translation_to_id");

                    b.Navigation("TranslationFrom");

                    b.Navigation("TranslationTo");
                });

            modelBuilder.Entity("bow.Domain.Entities.User", b =>
                {
                    b.Navigation("UserVocabularyItemProgresses");
                });

            modelBuilder.Entity("bow.Domain.Entities.VocabularyItem", b =>
                {
                    b.Navigation("SourceTranslations");

                    b.Navigation("TargetTranslations");

                    b.Navigation("UserVocabularyItemProgresses");
                });
#pragma warning restore 612, 618
        }
    }
}
