// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using bow.Infrastructure.Persistence;

#nullable disable

namespace bow.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260722201312_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("bow.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("LearningLanguage")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("learning_language");

                    b.Property<string>("LearningLevel")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("learning_level");

                    b.Property<string>("NativeLanguage")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("native_language");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at");

                    b.Property<long>("TelegramId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_id");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("TelegramId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_telegram_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("bow.Domain.Entities.UserWordProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("LastReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_reviewed_at");

                    b.Property<DateTime>("NextReviewAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_review_at");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("stage");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("WordId")
                        .HasColumnType("integer")
                        .HasColumnName("word_id");

                    b.HasKey("Id")
                        .HasName("pk_user_word_progresses");

                    b.HasIndex("WordId")
                        .HasDatabaseName("ix_user_word_progresses_word_id");

                    b.HasIndex("UserId", "NextReviewAt")
                        .HasDatabaseName("ix_user_word_progresses_user_id_next_review_at");

                    b.HasIndex("UserId", "WordId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_word_progresses_user_id_word_id");

                    b.ToTable("user_word_progresses", (string)null);
                });

            modelBuilder.Entity("bow.Domain.Entities.Word", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("language");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("level");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_words");

                    b.HasIndex("Text")
                        .HasDatabaseName("ix_words_text");

                    b.HasIndex("Language", "Level", "Text")
                        .HasDatabaseName("ix_words_language_level_text");

                    b.ToTable("words", (string)null);
                });

            modelBuilder.Entity("bow.Domain.Entities.WordTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<int>("SourceWordId")
                        .HasColumnType("integer")
                        .HasColumnName("source_word_id");

                    b.Property<int>("TargetWordId")
                        .HasColumnType("integer")
                        .HasColumnName("target_word_id");

                    b.HasKey("Id")
                        .HasName("pk_word_translations");

                    b.HasIndex("TargetWordId")
                        .HasDatabaseName("ix_word_translations_target_word_id");

                    b.HasIndex("SourceWordId", "TargetWordId")
                        .IsUnique()
                        .HasDatabaseName("ix_word_translations_source_word_id_target_word_id");

                    b.ToTable("word_translations", (string)null);
                });

            modelBuilder.Entity("bow.Domain.Entities.UserWordProgress", b =>
                {
                    b.HasOne("bow.Domain.Entities.User", "User")
                        .WithMany("UserWordProgresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_word_progresses_users_user_id");

                    b.HasOne("bow.Domain.Entities.Word", "Word")
                        .WithMany("UserWordProgresses")
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_word_progresses_words_word_id");

                    b.Navigation("User");

                    b.Navigation("Word");
                });

            modelBuilder.Entity("bow.Domain.Entities.WordTranslation", b =>
                {
                    b.HasOne("bow.Domain.Entities.Word", "SourceWord")
                        .WithMany("SourceTranslations")
                        .HasForeignKey("SourceWordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_word_translations_words_source_word_id");

                    b.HasOne("bow.Domain.Entities.Word", "TargetWord")
                        .WithMany("TargetTranslations")
                        .HasForeignKey("TargetWordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_word_translations_words_target_word_id");

                    b.Navigation("SourceWord");

                    b.Navigation("TargetWord");
                });

            modelBuilder.Entity("bow.Domain.Entities.User", b =>
                {
                    b.Navigation("UserWordProgresses");
                });

            modelBuilder.Entity("bow.Domain.Entities.Word", b =>
                {
                    b.Navigation("SourceTranslations");

                    b.Navigation("TargetTranslations");

                    b.Navigation("UserWordProgresses");
                });
#pragma warning restore 612, 618
        }
    }
}
